name: ubuntu-scripts
version: git
summary: Ubuntu Development Scripts
description: |
    Ubuntu Scripts is a collection of scripts to make the lives of Ubuntu
    developers easier. It is similar to the `ubuntu-dev-tools` project, but
    more liberal in what it will accept.
base: core18
confinement: devmode

parts:
    ubuntu-scripts:
        plugin: python
        python-version: python3
        source: .
        stage-packages:
            - python3-distro-info # get this from the distro, it's more up to date

apps:
    make-sru-tasks:
        command: bin/make-sru-tasks
