name: dev-scripts-ubuntu
version: git
summary: Ubuntu Development Scripts
description: |
    This is a collection of scripts to make the lives of Ubuntu developers
    easier. It is similar to the `ubuntu-dev-tools` project, but more suitable
    for 'throwing' scripts in.
base: core18

grade: devel
confinement: strict

parts:
    dev-scripts-ubuntu:
        plugin: python
        python-version: python3
        source: .
        build-packages:
            - libffi-dev
            - libssl-dev # both needed to build cryptography
        stage-packages:
            - python3-distro-info # get this from the distro, it's more up to date

apps:
    make-sru-tasks:
        command: bin/make-sru-tasks
        plugs:
            - network
